// <auto-generated />
using System;
using M365SecurityDashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace M365SecurityDashboard.Api.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresAppDbContext))]
    [Migration("20260903052327_TenantAlerting")]
    partial class TenantAlerting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AlertNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TargetKind", "TargetId");

                    b.ToTable("AlertNotes");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AlertPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityPattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("BaselineDays")
                        .HasColumnType("integer");

                    b.Property<double>("BaselineMultiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("LastTriggered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NotifyEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SuppressionMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("integer");

                    b.Property<int>("WindowMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("TenantId");

                    b.ToTable("AlertPolicies");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AlertPolicyTenantOverride", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NotifyEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int?>("Threshold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("TenantId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("TenantId");

                    b.ToTable("AlertPolicyTenantOverrides");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Prefix");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AppUser", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Email");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EntryHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("PrevHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorApp")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorUpn")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TargetName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Activity");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.ClientTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("ConsentGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCollectionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastCollectionStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LoginInstance")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MicrosoftTenantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MicrosoftTenantId");

                    b.ToTable("ClientTenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.CollectionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AlertsUpserted")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("GraphRequestCount")
                        .HasColumnType("integer");

                    b.Property<int>("GraphThrottleCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFailureDetails")
                        .HasColumnType("text");

                    b.Property<int>("SourceFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TenantId");

                    b.ToTable("CollectionRuns");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.GraphConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("LoginInstance")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GraphConfig");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.MetricsCounters", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("EvaluationsTotal")
                        .HasColumnType("bigint");

                    b.Property<long>("GraphRequestsTotal")
                        .HasColumnType("bigint");

                    b.Property<long>("GraphThrottledTotal")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("MetricsCounters");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("Target")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TriggeredAlertId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.HasIndex("TenantId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultRecipient")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DigestFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DigestHourUtc")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailDigest")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("FailureAlertThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("LastDigestAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastFailureAlertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastMspDigestAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MinSeverity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("MspDigestEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MspDigestHourUtc")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SmtpPassword")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("TeamsDigest")
                        .HasColumnType("boolean");

                    b.Property<bool>("TeamsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TeamsWebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WebhookDigest")
                        .HasColumnType("boolean");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("WebhookSigningSecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.ReportSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("HourUtc")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeCsv")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludePdf")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRunStatus")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ReportSchedules");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.SecurityAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Disposition")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PortalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Service")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("Service", "Severity", "IsResolved");

                    b.HasIndex("TenantId", "Service", "AlertType", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("SecurityAlerts");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.SuppressionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EntityPattern")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuppressedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SuppressedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("PolicyId");

                    b.HasIndex("TenantId");

                    b.ToTable("SuppressionRules");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TenantBaseline", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CapturedBy")
                        .HasColumnType("text");

                    b.Property<int>("ComplianceIssuesCount")
                        .HasColumnType("integer");

                    b.Property<int>("CriticalAlertsCount")
                        .HasColumnType("integer");

                    b.Property<int>("HighAlertsCount")
                        .HasColumnType("integer");

                    b.Property<double>("MfaCoveragePct")
                        .HasColumnType("double precision");

                    b.Property<int>("NonCompliantDevicesCount")
                        .HasColumnType("integer");

                    b.Property<int>("RiskyUsersCount")
                        .HasColumnType("integer");

                    b.Property<double>("SecureScorePct")
                        .HasColumnType("double precision");

                    b.HasKey("TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantBaselines");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TenantNotificationRouting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastDigestAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastFailureAlertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MinSeverity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("NotifyClient")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyMsp")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TeamsWebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantNotificationRoutings");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TrendSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ComplianceIssuesCount")
                        .HasColumnType("integer");

                    b.Property<int>("CriticalAlertsCount")
                        .HasColumnType("integer");

                    b.Property<int>("HighAlertsCount")
                        .HasColumnType("integer");

                    b.Property<double>("MfaCoveragePct")
                        .HasColumnType("double precision");

                    b.Property<int>("NonCompliantDevicesCount")
                        .HasColumnType("integer");

                    b.Property<int>("RiskyUsersCount")
                        .HasColumnType("integer");

                    b.Property<double>("SecureScorePct")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("TenantId");

                    b.ToTable("TrendSnapshots");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TriggeredAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AffectedEntities")
                        .HasColumnType("text");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("BelowThresholdStreakCount")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetricValue")
                        .HasColumnType("integer");

                    b.Property<bool>("Notified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SnoozedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("TriggeredAlerts");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.UserTenantAssignment", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("UserEmail", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("UserTenantAssignments");
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AlertNote", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AlertPolicy", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AlertPolicyTenantOverride", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.AlertPolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.ApiToken", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AuditEntry", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.AuditEvent", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.CollectionRun", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.MetricsCounters", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.NotificationLog", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.NotificationSettings", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.ReportSchedule", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.SecurityAlert", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.SuppressionRule", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TenantBaseline", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TenantNotificationRouting", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TrendSnapshot", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.TriggeredAlert", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M365SecurityDashboard.Api.Models.UserTenantAssignment", b =>
                {
                    b.HasOne("M365SecurityDashboard.Api.Models.ClientTenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M365SecurityDashboard.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
